name: CITests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...

  deploy-and-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Server
        run: |
          nohup go run main.go & echo $! > server.pid
          echo "Server starting..."

      - name: Health check
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          retry_wait_seconds: 10
          command: curl -f http://localhost:8080/

      - name: Test API
        run: |
          curl -X GET http://localhost:8080/users | jq .
          curl -X POST http://localhost:8080/users \
            -H "Content-Type: application/json" \
            -d '{"name":"test","email":"test@example.com"}' | jq .

      - name: Stop Server
        if: always()
        run: kill $(cat server.pid) || true
